language: ruby
rvm:
- 2.2.2
before_install: gem install bundler -v 1.10.5
branches:
  only:
  - master
  - "/^v[0-9]/"
bundler_args: "--without production --path=vendor/bundle"
cache:
  directories:
  - vendor/bundle
deploy:
  provider: rubygems
  api_key:
    secure: pQe3itljRcBv/Z8ywKhhr7Sg0fX4MzpGjCQabIQ0aQSh2JIIX9pHVyORNwmpS8ebGBxE3FLL+6l84AJ/UVYkTICqFJEv81T5a4dnkNwMzLUXu7KeYeZ5eiKhwEkBpFW9Y83IMyvrF6yxZT+8Wq/NZos4VXXo56hR6b8fagAjwgHhTQaS8ex414qAMl0PuVw/fVgH7S0R0QPIeE6c9U6mjBVvrqjRR655mF8UEEEBkrpjcEnpXt3qDRpU/s6gNJ+XSH1ZP388iDAcLNCaizN5qWGU8D2ojqT4weUs49rC3DPij2WJC0ORzIfExAHAv1LeVn6iVM5phEF8XsjFZg97PkS9AcCuzuDPPqRhIrZSXYHm0WcIRBZQHyqDRWkzgmbO+ugH1n3YjwJGNS6FFXTcvMNBJDGmXxZY1CesNqXFkjUG2l8JOxZsSMhtQfyHMhAIq2J2agC/nxMCtma5MhtYjwQDF+4Gp64EpTv8PA2n1eow5+z4PlsuHNdQmBmqI2V2u3V9kqbZQ1BJZmnuAYtoh247K1iCLHGJHuCyBEGOfn3ynA9zEYhbvQMM+06Q+UrOp/dqcYJOjaLN0/OlRkFZeKzLv704H+8gxXn2m2v1Jj5bQeM3Qxqei3o10k8PprQUoaPuQK3WRyr6M6yBHkH9IAOHYeE0f5lyPNesatetQWk=
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_TAG =~ ^v[0-9].*"
